"""astrbot_plugin_kugoumusic 的上游音乐 API 客户端包（自 core/api.py 拆分）。

子模块划分（原文件的分段注释 → 模块）：
    _core          复用 HTTP 会话、基础请求、工具
    _normalize     归一化
    _search        搜索
    _song          歌曲详情 / 取链、歌词、歌曲增强
    _comment       评论、评论扩展
    _rank          排行
    _playlist      歌手 / 专辑、歌单、新碟 / 推荐卡片 / 主题
    _recommend     推荐 / FM
    _mv            MV
    _account       设备注册 / 登录、用户（需登录）、账号扩展（需登录）、登录维护

本包对外符号与拆分前的 core/api.py 完全一致（``from ..core.api import X`` 与
``api.X`` 的既有用法不受影响）；模块级状态（HTTP 会话、设备 Cookie、特权缓存）
由 ``_core`` / 对应子模块持有，外部一律通过函数访问。
"""

from ._account import (
    artist_follow,
    artist_follow_newsongs,
    artist_unfollow,
    login_qq_qr_check,
    login_qq_qr_create,
    login_token_refresh,
    playhistory_upload,
    qr_check,
    qr_create,
    qr_key,
    register_dev,
    user_cloud,
    user_detail,
    user_follow,
    user_grade_info,
    user_history,
    user_listen,
    user_playlist,
    user_purchased_albums,
    user_purchased_songs,
)
from ._comment import (
    _parse_comments,
    comment_album,
    comment_count,
    comment_music,
    comment_playlist,
)
from ._core import (
    API_TIMEOUT_SEC,
    ERR_MESSAGES,
    ApiError,
    _cfg,
    _cfg_getter,
    _compose_cookie_str,
    _device_cookie,
    _err_msg_for,
    _get_base,
    _get_cookie,
    _get_session,
    _handle_response,
    _num,
    _query_safe_params,
    _session,
    _upstream_msg,
    cfg_int,
    close_session,
    extract_kugou_hash,
    get_session,
    request,
    safe_int,
    set_config_getter,
    set_device_cookie,
)
from ._mv import (
    video_url,
)
from ._normalize import (
    _album_info_of,
    _audio_info_of,
    _base_of,
    _cover,
    _data_of,
    _duration_text,
    _is_paid,
    _mix_id,
    _normalize_album,
    _normalize_all,
    _normalize_artist,
    _normalize_playlist,
    _normalize_song,
    _singers,
    _sub_dict,
)
from ._playlist import (
    album_songs,
    artist_audios,
    everyday_history,
    playlist_tags,
    playlist_tracks,
    rank_top,
    theme_playlist_tracks,
    theme_playlists,
    top_album,
    top_card,
    top_ip,
    top_playlists,
    yueku,
)
from ._rank import (
    rank_audio,
    rank_list,
    related_songs,
    top_song,
)
from ._recommend import (
    everyday_recommend,
    personal_fm,
)
from ._search import (
    hot_search,
    search,
    search_suggest,
)
from ._song import (
    _is_trial_url,
    _pick_url,
    ai_recommend,
    artist_albums,
    artist_lists,
    audio_by_hash,
    favorite_count,
    lyric,
    lyric_search,
    song_climax,
    song_url,
    song_url_best,
)

__all__ = [
    "API_TIMEOUT_SEC",
    "ApiError",
    "ERR_MESSAGES",
    "_album_info_of",
    "_audio_info_of",
    "_base_of",
    "_cfg",
    "_cfg_getter",
    "_compose_cookie_str",
    "_cover",
    "_data_of",
    "_device_cookie",
    "_duration_text",
    "_err_msg_for",
    "_get_base",
    "_get_cookie",
    "_get_session",
    "_handle_response",
    "_is_paid",
    "_is_trial_url",
    "_mix_id",
    "_normalize_album",
    "_normalize_all",
    "_normalize_artist",
    "_normalize_playlist",
    "_normalize_song",
    "_num",
    "_parse_comments",
    "_pick_url",
    "_query_safe_params",
    "_session",
    "_singers",
    "_sub_dict",
    "_upstream_msg",
    "ai_recommend",
    "album_songs",
    "artist_albums",
    "artist_audios",
    "artist_follow",
    "artist_follow_newsongs",
    "artist_lists",
    "artist_unfollow",
    "audio_by_hash",
    "cfg_int",
    "close_session",
    "comment_album",
    "comment_count",
    "comment_music",
    "comment_playlist",
    "everyday_history",
    "everyday_recommend",
    "extract_kugou_hash",
    "favorite_count",
    "get_session",
    "hot_search",
    "login_qq_qr_check",
    "login_qq_qr_create",
    "login_token_refresh",
    "lyric",
    "lyric_search",
    "personal_fm",
    "playhistory_upload",
    "playlist_tags",
    "playlist_tracks",
    "qr_check",
    "qr_create",
    "qr_key",
    "rank_audio",
    "rank_list",
    "rank_top",
    "register_dev",
    "related_songs",
    "request",
    "safe_int",
    "search",
    "search_suggest",
    "set_config_getter",
    "set_device_cookie",
    "song_climax",
    "song_url",
    "song_url_best",
    "theme_playlist_tracks",
    "theme_playlists",
    "top_album",
    "top_card",
    "top_ip",
    "top_playlists",
    "top_song",
    "user_cloud",
    "user_detail",
    "user_follow",
    "user_grade_info",
    "user_history",
    "user_listen",
    "user_playlist",
    "user_purchased_albums",
    "user_purchased_songs",
    "video_url",
    "yueku",
]
